[workspace]
members = ["tor_util"]

[profile.release]
debug = true
panic = "abort"

[source.crates-io]
registry = 'https://github.com/rust-lang/crates.io-index'
replace-with = 'vendored-sources'

[source.vendored-sources]
directory = 'vendor'

